### ISSUE TITLE
Remove Dependency on About Field(Ticket Field) in Settings

### ISSUE THREAD

**Issue by edalsted** [eddiestacks/mentors-suggestions#10]
Need to allow App to function if no About Field is defined in the App Settings.

**Comment by epritchard** [comment]
It's not possible to remove the entire dependency of this. This is due to the fact that we have an event defined for when the about field is changed, and we can't conditionally define that event only if an About Field ID was supplied.

So, instead, I've fixed up some of the code and added a default About Field ID of '0'. Accompanying this setting is helper text that states, "Enter field ID or leave at 0 if no field is available."
